### ISSUE TITLE
reportDecider npe bug

### ISSUE THREAD

**Issue by luyiisme** [alipay/sofa-lookout#47]
### Describe the bug

![image](https://user-images.githubusercontent.com/15273963/49081872-1dd5f980-f283-11e8-995e-eee4c8d93298.png)

old one may be null pointer

### Actual behavior

```
2018-11-27 16:05:10.588 [lookout-poller-2-HIGH-2000] WARN  com.alipay.lookout.remote.report.SchedulerPoller - failed to send metrics
java.lang.NullPointerException: null
   at com.alipay.lookout.remote.report.support.http.ReportDecider.refreshAddressCache(ReportDecider.java:102)
   at com.alipay.lookout.remote.report.support.http.ReportDecider.getAvailableAddress(ReportDecider.java:69)
```

### Environment

- SOFALookout version: 1.5.0
- JVM version (e.g. `java -version`):
- OS version (e.g. `uname -a`):
- Maven version:
- IDE version:

**Comment by luyiisme** [comment]
fixed in 1.5.1
